---
# this removes everything from the nodes for a clean start
- hosts: all
  tasks:
    - name: "Reset Kubernetes"
      shell: echo $(kubeadm reset -f && echo 'true')

    - name: "Remove docker images"
      shell: echo $(docker rmi --force $(docker images --all -q) && echo 'true')
      become: true

    - name: "apt-get update"
      apt:
        update_cache: yes
        autoclean: yes
        autoremove: yes

    - name: "apt-get purge packages"
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
        autoremove: yes
        force: yes
      with_items:
        - kubelet
        - kubeadm
        - kubectl
        - docker-ce

    - name: "Remove pod logging"
      shell: rm -rf /var/log/pods/*
      become: True

    - name: Reboot Message
      debug:
        msg: "REBOOTING ALL NODES."
    - name: Reboot (as needed)
      reboot:
        reboot_timeout: 3600
      tags:
        - boot
        - shutdown

