# - hosts: all
#   roles:
#     - common
#     - ssh
#     - sudo
#     # - firewall

# - hosts: worker, master
#   roles:
#     - kubeadm

# - hosts: master
#   roles:
#     - master

# - hosts: worker
#   roles:
#     - workers

- hosts: util
  roles:
    - geerlingguy.nfs
    - oefenweb.dnsmasq
  vars:
    nfs_exports: ["/nfs *(rw,sync,no_subtree_check,no_root_squash)"]
    dnsmasq_dnsmasq_d_files_present:
      local:
        - address=/local/192.168.8.102
        - address=/cluster/192.168.8.102
        - address=/ivh/192.168.8.102