- hosts: all
  tasks:
    # - name: Reboot (as needed)
    # reboot:
    #   reboot_timeout: 3600
    # when: cmdline or timezone or hostname or gpu_mem is changed
    # tags:
    #   - boot
    #   - shutdown

    - name: Reboot Message
      debug:
        msg: "REBOOTING ALL NODES."

    - name: Reboot
      shell: sleep 2 && shutdown -r now "Ansible Reboot"
      async: 1
      poll: 0
      ignore_errors: True
