# TODO,make a check on the installed version: not just IF it is there
- name: Determine if docker is installed
  stat:
    path: /usr/bin/docker
  register: docker_there
  ignore_errors: True

- name:    Install Docker prerequisites
  apt:     name={{item}} state=latest update_cache=yes
  when: docker_there.stat.exists == False
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg
  when: docker_there.stat.exists == False

- name: Add Docker APT repository
  when: docker_there.stat.exists == False
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ansible_distribution_release}} stable
    state: present

- name:    Install Docker
  when: docker_there.stat.exists == False
  apt:     name=docker-ce={{ docker_ce_version }} state=present

- name: Lock docker version to {{ docker_ce_version}}
  command: /usr/bin/apt-mark hold docker-ce
  when: docker_there.stat.exists == False

