---
# tasks file for kubeadm
- include: docker.yml

- name: Install python PIP
  apt:
    name: python-pip
    state: latest

- name: Install pip openshift
  pip:
    name: openshift
    state: latest

# https://gist.github.com/alexellis/fdbc90de7691a1b9edb545c17da2d975
- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Disable swap
  command: swapoff -a

# - name: remove swap
#   shell: sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: swap - remove current swaps from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^/[\S]+\s+none\s+swap '
    state: absent

- name: Pass bridged IPv4 traffic to iptables' chains
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present

# https://kubernetes.io/docs/setup/independent/install-kubeadm/

- name: Add Google Cloud Repo Key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes to Available apt Sources
  template:
    src: kubernetes.list
    dest: /etc/apt/sources.list.d/kubernetes.list
    owner: "{{ sshuser }}"
    group: "{{ sshuser }}"
    mode: 0644
  notify: "apt update"

- name: Install k8s {{ kubernetes_package_version }} Y'all
  apt:
    name: "{{ item }}={{ kubernetes_package_version }}"
    state: present
  with_items:
    - kubelet
    - kubeadm
    - kubectl
  notify: "restart machine"