- name: Install MetalLB (LoadBalancer)
  k8s:
    state: present
    src: https://raw.githubusercontent.com/google/metallb/v0.7.3/manifests/metallb.yaml

- name: Configure MetalLB
  k8s:
    state: present
    src: files/metallb.yaml


