- name: Install MetalLB
  shell: "kubectl apply -f https://raw.githubusercontent.com/google/metallb/v0.7.3/manifests/metallb.yaml"

- name: Configure MetalLB
  shell: "kubectl apply -f files/metallb.yaml"

