- name: apt-get update
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes
    cache_valid_time: 86400

- name: Install nessisary pkgs
  apt: name={{item}} state=latest
  with_items:
    - python-smbus
    - i2c-tools
    - python-apt

- name: Rename hostname
  shell: 'echo {{ inventory_hostname }} > /etc/hostname'

- name: Rename host in hosts
  lineinfile:
    path: "/etc/hosts"
    line: "127.0.0.1 {{ inventory_hostname }}"
    state: present

- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"

- name: Change password for user pi
  shell: 'echo pi:{{ PI_USER_PASSWORD }} | chpasswd'

- name: Disable bluetooth LE
  systemd:
    name: bluetooth
    enabled: no
    state: stopped

  when: not RASPBIAN_ENABLE_BLUETOOTH
  tags:
    - bluetooth

- name: Enable bluetooth LE
  systemd:
    name: bluetooth
    enabled: yes
    state: started
  when: RASPBIAN_ENABLE_BLUETOOTH
  tags:
    -bluetooth

- name: Set raspiconfig variable
  set_fact:
    raspiconfig: "{{ RASPICONFIG }}"

- name: Enable serial
  shell: "raspi-config nonint do_serial 0"
  when: raspiconfig.SERIAL

- name: Enable I2C
  shell: "raspi-config nonint do_i2c 0"
  when: raspiconfig.I2C

- name: Enable SPI
  shell: "raspi-config nonint do_spi 0"
  when: raspiconfig.SPI

- name: Enable Camera
  shell: "raspi-config nonint do_camera 0"
  when: raspiconfig.CAMERA

- name: Enable VNC
  shell: "raspi-config nonint do_vnc 0"
  when: raspiconfig.VNC

- name: Enable OneWire
  shell: "raspi-config nonint do_onewire 0"
  when: raspiconfig.ONEWIRE

- name: Enable Remote GPIO
  shell: "raspi-config nonint do_rgpio 0"
  when: raspiconfig.RGPIO

- name: Disable serial
  shell: "raspi-config nonint do_serial 1"
  when: raspiconfig.SERIAL

- name: Disable I2C
  shell: "raspi-config nonint do_i2c 1"
  when: not raspiconfig.I2C

- name: Disable SPI
  shell: "raspi-config nonint do_spi 1"
  when: not raspiconfig.SPI

- name: Disable Camera
  shell: "raspi-config nonint do_camera 1"
  when: not raspiconfig.CAMERA

- name: Disable VNC
  shell: "raspi-config nonint do_vnc 1"
  when: not raspiconfig.VNC

- name: Disable OneWire
  shell: "raspi-config nonint do_onewire 1"
  when: not raspiconfig.ONEWIRE

- name: Disable Remote GPIO
  shell: "raspi-config nonint do_rgpio 1"
  when: not raspiconfig.RGPIO

- name: Ensure hostname set
  hostname:
    name: "{{ inventory_hostname }}"
  when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')
  register: hostname
  tags: hostname

- name: Ensure hostname is in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_default_ipv4.address }}.+$"
    line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"
  register: hostname
  tags: hostname

- name: gpu mem check
  shell: cat /boot/config.txt | grep gpu_mem
  changed_when: false
  register: gpu_mem_check
  ignore_errors: yes

- name: reduce gpu memory
  become: true
  become_user: root
  lineinfile:
    path: /boot/config.txt
    line: gpu_mem=16
  register: gpu_mem
  when: gpu_mem_check.stdout == ""

- name: Enabling cgroup options at boot
  copy:
    src: cmdline.txt
    dest: /boot/cmdline.txt
    owner: root
    group: root
    mode: 0755
  register: cmdline
  tags:
    - boot

- name: set timezone to Amsterdam
  timezone:
    name: Europe/Amsterdam
  register: timezone

# - name: Reboot (as needed)
#  reboot:
#    reboot_timeout: 3600
#  when: cmdline or timezone or hostname or gpu_mem is changed
#  tags:
#    - boot
#    - shutdown
- name: Reboot Message
  debug:
    msg: "A reboot is required but the reboot module is a little wonky. Hopefully someone fixes this soon."
  when: cmdline or timezone or hostname or gpu_mem is changed

- name: Reboot
  shell: sleep 2 && shutdown -r now "Ansible Reboot"
  async: 1
  poll: 0
  ignore_errors: True

- name: Wait for Reboot
  local_action: wait_for
  args:
    host: "{{ inventory_hostname }}"
    state: started
  become: False