PI_USER_PASSWORD: "k8siscool"

# Bluetooth LE
RASPBIAN_ENABLE_BLUETOOTH: false

# raspi-config interface settings

RASPICONFIG:
  SERIAL: true
  CAMERA: false
  VNC: false
  SPI: false
  I2C: true
  ONEWIRE: false
  RGPIO: false