---
# tasks file for minions
- name: Reset Kubernetes
  shell: kubeadm reset -f
  when: clean_install
  register: kubeadm_reset

- name: Join Kubernetes Cluster
  shell: kubeadm join --ignore-preflight-errors=all --token {{ token }} {{ groups['master'][0] }}:6443 --discovery-token-unsafe-skip-ca-verification
  when: kubeadm_reset is not skipped
  notify: "poke kubelet"
