- name: NOPASSWD sudo
  lineinfile: "dest=/etc/sudoers.d/{{ sshuser }}
    create=yes state=present mode=0440
    owner=root group=root
    line='{{ sshuser }} ALL=(ALL) NOPASSWD: ALL'"
  notify: "restart machine"