- name: NOPASSWD sudo
  lineinfile: "dest=/etc/sudoers.d/pi
    create=yes state=present mode=0440
    owner=root group=root
    line='pi ALL=(ALL) NOPASSWD: ALL'"

- name: Reboot Message
  debug:
    msg: "REBOOTING ALL NODES."

- name: Reboot (as needed)
  reboot:
    reboot_timeout: 3600
  tags:
    - boot
    - shutdown