- name: Install nessisary pkgs
  apt: name={{item}} state=present
  with_items:
    - build-essential
    - python-dev
    - python-pip
    - python-imaging
    - python-smbus
    - git

# - name: Download SSD1306 library
#   git: repo=https://github.com/adafruit/Adafruit_Python_SSD1306.git dest=~/lcdlib/
#     recursive=yes accept_hostkey=yes update=yes track_submodules=yes force=yes
#   ignore_errors: yes
#   become: false

- name: Copy the code to the user folder
  copy:
    src: files/
    dest: /home/pi/
    owner: pi
    group: pi
    mode: u=rwX,g=rX,o=rX

- name: Make directory tree readable
  file:
    path: /home/pi/lcdlib
    mode: u=rwX,g=rX,o=rX
    recurse: yes

- name: Install the library
  command: bash -lc "cd /home/pi/lcdlib/ && sudo python setup.py install"
  become: false

- name: Add python display program to startup
  lineinfile:
    path: "/etc/rc.local"
    insertbefore: 'exit 0'
    line: "sudo python /home/pi/disp.py  &"
    state: present

# - name: Reboot (as needed)
#  reboot:
#    reboot_timeout: 3600
#  when: cmdline or timezone or hostname or gpu_mem is changed
#  tags:
#    - boot
#    - shutdown
- name: Reboot Message
  debug:
    msg: "A reboot is required but the reboot module is a little wonky. Hopefully someone fixes this soon."
  when: cmdline or timezone or hostname or gpu_mem is changed

- name: Reboot
  shell: sleep 2 && shutdown -r now "Ansible Reboot"
  async: 1
  poll: 0
  ignore_errors: True

- name: Wait for Reboot
  local_action: wait_for
  args:
    host: "{{ inventory_hostname }}"
    state: started
  become: False
